#!/bin/bash

cd VerivalUiautomator/

echo -e "########################\n\tBUILD\n########################"
ant build
if [[ "$?" -ne "0" ]]
then
	echo -e "\nErro no BUILD. Saindo..."
	exit -1
fi

echo -e "\n########################\n\tDEPLOY\n########################"
adb push src/resources/strings_pt-BR.properties /data/local/tmp/
adb push src/resources/strings_en-US.properties /data/local/tmp/
adb push bin/VerivalUiautomator.jar /data/local/tmp/
if [[ "$?" -ne "0" ]]
then
	echo -e "\nErro no DEPLOY. Saindo..."
	exit -1
fi

echo -e "\n########################\n\tTESTS\n########################"
adb shell uiautomator runtest VerivalUiautomator.jar -c br.unb.vvs.uiautomator.TestLigaDesligaFuncionalidades | grep -v INSTRUMENTATION_STATUS
adb shell uiautomator runtest VerivalUiautomator.jar -c br.unb.vvs.uiautomator.TestEnviaVerificaEmail | grep -v INSTRUMENTATION_STATUS